apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-basicauth-secret
  namespace: route
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: traefik-basicauth-secret
    creationPolicy: Owner
  data:
    - secretKey: tfkuser
      remoteRef:
        key: ec5fc8a5-9331-42fd-8a0b-b2f401027f09
