apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: route

resources:
  - namespace.yaml
  - role.yaml
  - service-account.yaml
  - role-binding.yaml
  - deployment.yaml
  - services.yaml
  - wildcard.vextech.dev.certificate.yaml
  - config/middlewares.yaml
  - config/auth-chains.yaml
  - config/tls-options.yaml
  - config/tls-store.yaml
  - basicauth-mw.externalsecret.yaml
  - dashboard.ingressroute.yaml

configMapGenerator:
  - name: traefik-static
    files:
      - traefik.yaml=config/traefik.yaml
    options:
      disableNameSuffixHash: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
