apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: route

resources:
  - namespace.yaml
  - wildcard.vextech.dev.certificate.yaml
  - config/middlewares.yaml
  - config/auth-chains.yaml
  - basicauth-mw.externalsecret.yaml
  - dashboard.ingressroute.yaml
  - network-policy.yaml

helmCharts:
- name: traefik
  repo: https://traefik.github.io/charts
  version: 36.1.0
  releaseName: traefik
  namespace: route
  valuesFile: values.yaml
  includeCRDs: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
