global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  enabled: true
  insecure: false
  disableDashboardAd: true
hub:
  enabled: false
  apimanagement:
    enabled: false
  experimental:
    aigateway: false

logs:
  general:
    level: "DEBUG"
  access:
    enabled: true
    filePath: "/data/traefik.log"
    filters:
      statuscodes: "204-299,400-599"
    fields:
      defaultMode: keep
      headers:
        defaultMode: drop
        names:
          User-Agent: keep

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowEmptyServices: true
    disableClusterScopeResources: true
    #namespaces: [ "whoami", "longhorn-system", "kube-system", "argocd", "monitoring", "media" ]

ports:
  web: null
  websecure:
    asDefault: true
    port: 8443
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
      options: "default"
    middlewares:
      - route-auth-ratelimit@kubernetescrd
      - route-compress-auth@kubernetescrd
      - route-auth-headers@kubernetescrd
    forwardedHeaders:
      trustedIPs:
        - "192.168.0.0/16"       # home/LAN range
        - "10.0.0.0/8"           # internal range
        - "100.0.0.0/8"          # tailscale range
        # - "172.16.0.0/12"
        - "127.0.0.1/32"         # loopback
        - "173.245.48.0/20"      # Cloudflare IPs
        - "103.21.244.0/22"      # Cloudflare IPs

tlsStore:
  default:
    certificates:
      - secretName: wildcard.vextech.dev-tls
    defaultCertificate:
      secretName: wildcard.vextech.dev-tls

tlsOptions:
  default:
    minVersion: "VersionTLS12"
    cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   # TLS 1.2
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    # TLS 1.2
    - TLS_AES_256_GCM_SHA384                  # TLS 1.3
    - TLS_CHACHA20_POLY1305_SHA256            # TLS 1.3
    curvePreferences:
    - CurveP521
    - CurveP384
    sniStrict: false

experimental:
  plugins:
    cloudflarewarp:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: v1.3.3
    # bouncer:
    #   moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
    #   version: "v1.4.2"

deployment:
  enabled: true
  kind: Deployment # ( Deployment | Daemonset )
  replicas: 2
  podLabels:
    app: traefik
    homelab/ingress: "true"

service:
  enabled: true
  single: true
  type: LoadBalancer
  labels:
    traefik.io/external-lb: "true"
    k8s.io/ingress-controller: "true"
  annotations:
    io.cilium/lb-ipam-ips: "from-pool"   # This tells Cilium to assign from the pool
#   io.cilium/lb-ipam-ips: "192.168.254.10"
  spec:
    externalTrafficPolicy: Local

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

persistence:
  enabled: true
  name: data
  storageClass: "longhorn"
  accessMode: ReadWriteMany
  size: 1Gi

rbac:
  enabled: true
  namespaced: false

securityContext:
  capabilities:
    drop: [ "ALL" ]
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

podSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true
