apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - 99-promtheus.ingressroute.yaml
  - 99-grafana.ingressroute.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 73.2.0 # renovate: docker=ghcr.io/prometheus-community/charts/kube-prometheus-stack
    releaseName: prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true
