tunnelConfig:
  name: K3s-VexTech
  protocol: auto # auto | http2 | h2mux | quic
  noAutoUpdate: true
  logLevel: debug
  transportLogLevel: debug

ingress:
  - hostname: "*.vextech.dev"
    service: https://traefik.route.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      originServerName: "*.vextech.dev"
      logHeaders: true
      headers:
        - name: CF-Connecting-IP
        - name: X-Real-IP
        - name: CF-IPCountry
        - name: CF-Ray
        - name: CF-Visitor
        - name: CF-Device-Type
        - name: CF-IPCITY
        - name: CF-IPCONTINENT
        - name: CF-IPLATITUDE
        - name: CF-IPLONGITUDE
        - name: CF-IPREGION
        - name: X-Forwarded-For
        - name: Accept-Language
        - name: User-Agent
        - name: True-Client-IP
        - name: CF-IPCountry
        - name: CF-RAY
        - name: CF-Worker
        - name: CF-Client-Bot
        - name: CF-Bot-Score
        - name: CF-Challenge
        - name: CF-Bot-Management-Tag
  - hostname: vextech.dev
    service: https://traefik.route.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      originServerName: vextech.dev
      logHeaders: true
      headers:
        - name: CF-Connecting-IP
        - name: X-Real-IP
        - name: CF-IPCountry
        - name: CF-Ray
        - name: CF-Visitor
        - name: CF-Device-Type
        - name: CF-IPCITY
        - name: CF-IPCONTINENT
        - name: CF-IPLATITUDE
        - name: CF-IPLONGITUDE
        - name: CF-IPREGION
        - name: X-Forwarded-For
        - name: Accept-Language
        - name: User-Agent
  - service: http_status:404


