apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project.yaml
- application-set.yaml
- networking
- storage
- controllers
# - deployment
# - auth

generatorOptions:
  disableNameSuffixHash: true
