apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- namespace.yaml
- role.yaml
- role-binding.yaml
- bitwarden-certificate.yaml
- bitwarden-store.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.17.0
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: values.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-4"

# Create a Kubernetes secret for the Bitwarden API token.
# This secret is used by the External Secrets operator to access Bitwarden.
# Make sure to replace <your-token> with your actual Bitwarden API token.
# kubectl create secret generic bitwarden-access-token \
#   --namespace external-secrets \
#   --from-literal=token=<your-token>
