apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: external-no-auth
  namespace: route
spec:
  chain:
    middlewares:
      - name: cloudflarewarp
      #- name: crowdsec-bouncer
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: local-no-auth
  namespace: route
spec:
  chain:
    middlewares:
      - name: auth-ratelimit
      - name: auth-headers
      - name: compress-auth
      # - name: local-ipallowlist
      # - name: crowdsec-bouncer
# ---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: authelia-auth
#   namespace: route
# spec:
#   chain:
#     middlewares:
#       - name: auth-ratelimit
#       - name: auth-headers
#       - name: authelia
#       - name: local-ipallowlist
#       - name: compress-auth
#       #- name: crowdsec-bouncer
