apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: route
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
    hostsProxyHeaders:
      - X-Forwarded-Host
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow"
      X-XSS-PROTECTION: "1, mode=block"
      x-powered-by: ""
      server: ""
    stsIncludeSubdomains: true
    stsSeconds: 31536000
    stsPreload: true
    forceSTSHeader: true
    customFrameOptionsValue: "SAMEORIGIN"
    accessControlMaxAge: 100
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "same-origin"
    frameDeny: true
    permissionsPolicy: >-
      accelerometer=(), autoplay=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), screen-wake-lock=(), sync-xhr=(), xr-spatial-tracking=(), interest-cohort=()
    contentSecurityPolicy: >-
      default-src 'none'; img-src 'self' https: data: blob: http://*.vextech.dev; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com/; style-src-attr 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: https://*.vextech.dev; worker-src 'self' blob:; connect-src 'self' https://*.vextech.dev http://*.vextech.dev; object-src 'none'; frame-ancestors 'self' *; base-uri 'self'; form-action 'self'; frame-src 'self' https://*.vextech.dev; media-src 'self'; font-src 'self' data:; manifest-src 'self'; require-trusted-types-for 'script'
