apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jellyfin-mw
  namespace: route
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
    hostsProxyHeaders:
      - X-Forwarded-Host
    customResponseHeaders:
      X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      X-XSS-PROTECTION: "1"
      server: ""
    stsIncludeSubdomains: true
    stsSeconds: 31536000
    stsPreload: true
    forceSTSHeader: true
    customFrameOptionsValue: "SAMEORIGIN"
    accessControlMaxAge: 100
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "same-origin"
    frameDeny: true
    permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
    # Optional CSP below — uncomment if you decide to use it
    # contentSecurityPolicy: >-
    #   default-src 'none'; img-src 'self' https: data: blob:; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline' https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/ https://ctalvio.github.io https://fonts.googleapis.com/; style-src-attr 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' blob: https://www.gstatic.com https://www.youtube.com; worker-src 'self' blob:; connect-src 'self'; object-src 'none'; frame-ancestors 'self'; base-uri 'self'; form-action 'self'; font-src 'self'; require-trusted-types-for 'script'
