apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153

        # Kubernetes service domain
        kubernetes cluster.local kube.vextech.dev in-addr.arpa ip6.arpa {
            pods insecure
            ttl 30
            fallthrough
        }

        # Forwarding to external DNS servers for non-cluster queries
        forward . 192.168.10.1 {
            policy sequential
        }

        cache 30
        loop
        reload
        loadbalance
    }
