apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-role.yaml
  - 00-service-account.yaml
  - 01-role-binding.yaml
  - 02-configmap.yaml
  - 02-deployment.yaml
  - 02-services.yaml
