loki:
  replicas: 1
  # Use filesystem persistence, suitable for a single-node setup
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn # IMPORTANT: Match your StorageClass
  # Resource tuning for homelab
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  # # Use a simple, single-binary deployment mode
  # commonConfig:
  #   replication_factor: 1
  # storage:
  #   type: 'filesystem'
# Disable other components in the chart, we will manage them separately
grafana:
  enabled: false
prometheus:
  enabled: false
promtail:
  enabled: false
gateway:
  enabled: false
