global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  insecure: false
  dashboard: true
  disableDashboardAd: true

log:
  level: INFO  # ( DEBUG | INFO )

providers:
  kubernetesCRD:
    allowCrossNamespace: true

accessLog:
  filePath: "/var/log/traefik.log"
  format: json
  filters:
    statusCodes:
      - "204-299"
      - "400-599"
  bufferingSize: 100
  fields:
    #defaultMode: keep
    headers:
      defaultMode: drop
      names:
        User-Agent: keep

http:
  serversTransports:
    ignorecert:
      insecureSkipVerify: true

entrypoints:
  websecure:
    address: ':443'
    asDefault: true
    forwardedHeaders:
      trustedIPs:
        - "192.168.0.0/16"       # home/LAN range
        - "10.0.0.0/8"           # internal range
        - "100.0.0.0/8"          # tailscale range
        - "172.16.0.0/12"
        - "127.0.0.1/32"         # loopback
        - "173.245.48.0/20"      # Cloudflare IPs
        - "103.21.244.0/22"      # Cloudflare IPs
    http3:
      advertisedPort: 443

experimental:
  plugins:
    cloudflarewarp:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: "v1.3.3"
#     bouncer:
#       moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
#       version: "v1.4.2"
