apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cloudflarewarp
  namespace: route
spec:
  plugin:
    cloudflarewarp:
      disableDefault: "false"
      trustip:
        - 10.0.0.0/8
