apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
spec:
  description: Project for core infrastructure controllers
  sourceRepos:
    - 'https://github.com/masonfx/k3s-lab'
  destinations:
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
    - namespace: 'kube-system'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
