apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudflared

namespace: cloudflared

resources:
  - namespace.yaml
  - daemonset.yaml
  - tunnel.externalsecret.yaml
  - network-policy.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: config
    files:
      - config.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
