apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cf-network-policy
  namespace: cloudflared
spec:
  endpointSelector:
    matchLabels:
      app: cloudflared
  ingress:
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "2000"
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "2000"
  egress:
    - toEndpoints:
        - matchLabels:
            app: traefik
            io.kubernetes.pod.namespace: route
      toPorts:
        - ports:
            - port: "8443"
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "7844"
