apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: route
spec:
  type: LoadBalancer  # Use NodePort or ClusterIP if needed
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: websecure
      port: 443
      targetPort: websecure
