apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard.vextech.dev
  namespace: route
spec:
  secretName: wildcard.vextech.dev-tls
  # secretTemplate:
  #   annotations:
  #     reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  #     reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "gateway"
  #     reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  #     reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "gateway"
  dnsNames:
    - "*.vextech.dev"
    - "vextech.dev"
    - traefik.route.svc.kube.vextech.dev
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
