apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard.vextech.dev
  namespace: route
spec:
  secretName: wildcard.vextech.dev-tls
  dnsNames:
    - "*.vextech.dev"
    - "vextech.dev"
    - traefik.route.svc.kube.vextech.dev
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
