apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: route

resources:
  - 00-namespace.yaml
  - 00-role.yaml
  - 00-service-account.yaml
  - 01-role-binding.yaml
  - 02-deployment.yaml
  - 02-services.yaml
  - 03-wildcard.vextech.dev.certificate.yaml
  - config/12-middlewares.yaml
  - config/13-auth-chains.yaml
  - config/14-tls-options.yaml
  - config/14-tls-store.yaml
  # - 99-tcproute.yaml
  # - 99-httproute.yaml
  - 99-traefik-dashboard.ingressroute.yaml

secretGenerator:
  - name: traefik-auth-secret
    files:
      - secrets/users
    options:
      disableNameSuffixHash: true

configMapGenerator:
  - name: traefik-static
    files:
      - traefik.yaml=config/11-traefik.yaml
    options:
      disableNameSuffixHash: true
