apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - dashboard.ingress-route.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.0.14
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"


# Get the initial admin password
# kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d
