apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - namespace.yaml
  - recurring-job.yaml
  - ingress-route.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.9.0
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml
    includeCRDs: true

patches:
  - path: 11-backup.yaml
    target:
      kind: ConfigMap
      name: longhorn-default-resource
      namespace: longhorn-system
