apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - role.yaml
  - service-account.yaml
  - role-binding.yaml
  - configmap.yaml
  - deployment.yaml
  - services.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-8"
