apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: cert-manager
  # labels:
  #   app.kubernetes.io/name: bitwardensecret
  #   app.kubernetes.io/instance: cert-manager-secrets
  #   app.kubernetes.io/managed-by: kustomize
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: 7cc906d9-2de7-418c-a1ae-b2e8000abc5b
  - secretKey: email
    remoteRef:
      key: ea4e2d0e-1ba9-4ffd-9b7c-b2e80005d9a8
