apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
  - 00-namespace.yaml
  - 01-letsencrypt.clusterissuer.yaml
  - 01-bitwarden.clusterissuer.yaml
  - cloudflare-api.externalsecret.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.17.2 # renovate: github-releases=cert-manager/cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
