apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"

resources:
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.83.0/stripped-down-crds.yaml
  - prometheus.ingress-route.yaml
  - grafana.ingress-route.yaml
  - alertmanager.ingress-route.yaml
  - rbac.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 73.2.0 # renovate: docker=ghcr.io/prometheus-community/charts/kube-prometheus-stack
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: false
