apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-dashboard
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`prometheus.vextech.dev`)
    kind: Rule
    services:
    - name: kube-prometheus-stack-prometheus
      port: 9090
    middlewares:
      - name: local-no-auth
        namespace: route
  tls: {}

