grafana:
  enabled: true
  replicas: 1
  adminPassword: "admin" # CHANGE THIS default password
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # Pre-load dashboards from the community
  # These are sourced from grafana.com/grafana/dashboards/
  dashboardProviders:
    grafana-com-dashboards:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: 'file'
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      # Node Exporter Full Dashboard
      node-exporter:
        gnetId: 1860
        revision: 36
        datasource: Prometheus
      # Kubernetes Cluster Overview
      k8s-cluster:
        gnetId: 3119
        revision: 24
        datasource: Prometheus
      # Cilium Dashboard
      cilium:
        gnetId: 10922
        revision: 23
        datasource: Prometheus

kubelet:
  enabled: false

kubeStateMetrics:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheusOperator:
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
      # This forces the operator to wait for the webhook to be ready
      # which prevents the "secret not found" mounting error.
      priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d
    resources:
      requests:
        cpu: 250m
        memory: 750Mi
      limits:
        cpu: 1
        memory: 1.5Gi
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

alertmanager:
  alertmanagerSpec:
    replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 250Mi
  ingress:
    enabled: false
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
