grafana:
  enabled: true
  replicas: 1
  adminPassword: "admin" # CHANGE THIS default password
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

kubeStateMetrics:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheusOperator:
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
      # This forces the operator to wait for the webhook to be ready
      # which prevents the "secret not found" mounting error.
      priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  prometheusSpec:
    replicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 750Mi
      limits:
        cpu: 1
        memory: 1.5Gi
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

alertmanager:
  alertmanagerSpec:
    replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 250Mi
  ingress:
    enabled: false
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
